#!/bin/bash

set -eu

bindir=$(realpath "$(dirname "$0")")

. "$bindir"/functions.bash

USAGE="Usage: $0"

rundir="$bindir"/app
go () {
    cwd "$rundir" ./Main
}

also () {
    then="$1"
    shift
    "$@" && "$then"
}

cmd also go ghc -isrc app/Main.hs
